// Библиотека скиллов. used — сколько раз скилл реально вызывался в прошлых сессиях.
window.CATEGORIES = [
  { id: "orient", name: "Ориентация и память", emoji: "🧭", color: "#c8793b" },
  { id: "think", name: "Планирование и мышление", emoji: "🧠", color: "#b5654a" },
  { id: "code", name: "Код и архитектура", emoji: "🛠", color: "#8a6a3b" },
  { id: "design", name: "Дизайн и фронтенд", emoji: "🎨", color: "#d0894f" },
  { id: "visual", name: "Изображения и визуал", emoji: "🖼", color: "#b8804a" },
  { id: "text", name: "Тексты и документы", emoji: "✍️", color: "#9c5b3f" },
  { id: "seo", name: "SEO", emoji: "🔎", color: "#7f7a3c" },
  { id: "law", name: "Право РФ (legitAgent)", emoji: "⚖️", color: "#8c4f3a" },
];

window.SKILLS = [
  // Ориентация и память
  { id: "graphify", cat: "orient", used: 23, d: "Строит граф знаний проекта и отвечает по нему: архитектура, связи, «где живёт X» — без чтения файлов подряд." },
  { id: "claude-mem:mem-search", cat: "orient", d: "Поиск по памяти прошлых сессий: «как мы это уже решали?»." },
  { id: "claude-mem:learn-codebase", cat: "orient", d: "Разом загружает весь репозиторий в память claude-mem (~5 минут)." },
  { id: "claude-mem:smart-explore", cat: "orient", d: "Экономная разведка кода через AST-структуру вместо полного чтения файлов." },
  { id: "claude-mem:timeline-report", cat: "orient", d: "Отчёт-история развития проекта по сессиям." },
  { id: "claude-mem:standup", cat: "orient", d: "Короткий стендап: что сделано, что дальше, что блокирует." },
  { id: "claude-mem:make-plan", cat: "orient", d: "План реализации с опорой на документацию и прошлый контекст." },
  { id: "claude-mem:do", cat: "orient", d: "Исполняет план фазами через субагентов." },
  { id: "handoff", cat: "orient", d: "Сжимает текущий разговор в документ-передачу для другого агента." },
  { id: "claude-handoff", cat: "orient", d: "Передаёт работу свежему фоновому агенту, который сразу продолжает." },
  { id: "find-skills", cat: "orient", used: 1, d: "Находит и ставит подходящие скиллы под задачу «как сделать X»." },
  { id: "ask-matt", cat: "orient", d: "Роутер: подсказывает, какой скилл или флоу подходит к ситуации." },
  { id: "academy-guide", cat: "orient", d: "Подбирает курсы и туториалы Claude Academy по вопросу о продуктах Claude." },

  // Планирование и мышление
  { id: "grilling", cat: "think", used: 1, d: "Жёсткий допрос по плану или идее — вскрывает слабые места до старта." },
  { id: "grill-me", cat: "think", d: "Безжалостное интервью, чтобы заточить план или дизайн." },
  { id: "grill-with-docs", cat: "think", d: "То же интервью, но попутно пишет ADR и глоссарий." },
  { id: "loop-me", cat: "think", d: "Допрос по спецификации воркфлоу, которые хочется построить." },
  { id: "to-spec", cat: "think", d: "Превращает обсуждение в спеку и публикует в трекер — без лишних вопросов." },
  { id: "to-tickets", cat: "think", d: "Режет план на тикеты-«трассеры» с явными зависимостями." },
  { id: "to-questionnaire", cat: "think", d: "Делает опросник для решения, которое должен принять кто-то другой." },
  { id: "wayfinder", cat: "think", d: "План огромной работы как карта решений-тикетов, закрываемых по одному." },
  { id: "triage", cat: "think", d: "Прогоняет issues и PR через стейт-машину триажа и пишет брифы для агентов." },
  { id: "domain-modeling", cat: "think", d: "Доменная модель проекта: CONTEXT.md, термины, ADR." },
  { id: "research", cat: "think", d: "Исследует вопрос по первоисточникам и сохраняет выводы в Markdown." },
  { id: "prototype", cat: "think", d: "Одноразовый прототип, чтобы быстро ответить на вопрос дизайна или логики." },
  { id: "teach", cat: "think", d: "Обучает новой теме или навыку прямо в рабочем пространстве." },
  { id: "wait-what", cat: "think", d: "«Стоп, не понял» — заставляет переформулировать последнее сообщение." },
  { id: "discernment-nudge", cat: "think", d: "После важного ответа подсказывает, что стоит перепроверить самому." },

  // Код и архитектура
  { id: "implement", cat: "code", d: "Реализует работу по спеке или набору тикетов." },
  { id: "tdd", cat: "code", d: "Разработка через тесты: red → green → refactor." },
  { id: "code-review", cat: "code", d: "Ревью изменений по двум осям: стандарты репо и корректность." },
  { id: "run", cat: "code", used: 3, d: "Запускает приложение проекта и показывает, что изменение реально работает." },
  { id: "schedule", cat: "code", used: 3, d: "Облачные агенты по расписанию (cron) и разовые отложенные запуски." },
  { id: "update-config", cat: "code", used: 1, d: "Настройка Claude Code через settings.json: хуки, права, env." },
  { id: "codebase-design", cat: "code", d: "Общий словарь для проектирования «глубоких» модулей и их швов." },
  { id: "improve-codebase-architecture", cat: "code", d: "Ищет места для углубления модулей и выдаёт визуальный HTML-отчёт." },
  { id: "setup-ts-deep-modules", cat: "code", d: "dependency-cruiser в TS-репо: каждый пакет — глубокий модуль." },
  { id: "setup-pre-commit", cat: "code", d: "Husky + lint-staged + типы + тесты на pre-commit." },
  { id: "git-guardrails-claude-code", cat: "code", d: "Хуки, блокирующие опасные git-команды (reset --hard, push -f…)." },
  { id: "resolving-merge-conflicts", cat: "code", d: "Аккуратно разруливает конфликты merge/rebase." },
  { id: "migrate-to-shoehorn", cat: "code", d: "Переводит тесты с `as` на @total-typescript/shoehorn." },
  { id: "full-output-enforcement", cat: "code", d: "Запрещает обрезки и заглушки — код выдаётся целиком." },
  { id: "mcp-builder", cat: "code", d: "Гайд по созданию качественных MCP-серверов." },
  { id: "wizard", cat: "code", d: "Генерирует интерактивный bash-мастер для шагов, которые может сделать только человек." },
  { id: "scaffold-exercises", cat: "code", d: "Каркас упражнений: задачи, решения, объяснения." },
  { id: "skill-creator", cat: "code", d: "Создаёт, улучшает и тестирует новые скиллы." },

  // Дизайн и фронтенд
  { id: "frontend-design", cat: "design", used: 1, d: "Осознанная эстетика нового UI: направление, типографика, характер." },
  { id: "impeccable", cat: "design", used: 1, d: "Полировка интерфейса до безупречного состояния." },
  { id: "design-taste-frontend", cat: "design", d: "Анти-«AI-slop» для лендингов и портфолио: сам выбирает направление дизайна." },
  { id: "high-end-visual-design", cat: "design", d: "Дизайн уровня топ-агентства: шрифты, отступы, тени, анимации." },
  { id: "minimalist-ui", cat: "design", d: "Редакционный минимализм: тёплый монохром, bento-сетки, пастель." },
  { id: "industrial-brutalist-ui", cat: "design", d: "Брутализм: швейцарская типографика и эстетика военного терминала." },
  { id: "redesign-existing-projects", cat: "design", d: "Апгрейд существующего сайта до премиума без поломки функций." },
  { id: "stitch-design-taste", cat: "design", d: "DESIGN.md для Google Stitch с премиальными правилами UI." },
  { id: "image-to-code", cat: "design", d: "Сначала генерирует макет-картинку, затем точно верстает по нему." },
  { id: "web-artifacts-builder", cat: "design", d: "Сложные HTML-артефакты на React + Tailwind + shadcn/ui." },
  { id: "webapp-testing", cat: "design", d: "Проверка локального веб-приложения через Playwright." },
  { id: "theme-factory", cat: "design", d: "10 готовых тем (цвета + шрифты) для слайдов, доков, лендингов." },
  { id: "brand-guidelines", cat: "design", d: "Фирменные цвета и типографика Anthropic." },

  // Изображения
  { id: "kie-image-gen", cat: "visual", used: 1, d: "Генерация и правка изображений через kie.ai (nano-banana) прямо curl-ом." },
  { id: "brandkit", cat: "visual", d: "Премиальные брендбуки: логосистемы, айдентика, визуальный мир." },
  { id: "canvas-design", cat: "visual", d: "Постеры и арт в PNG/PDF на основе дизайн-философии." },
  { id: "algorithmic-art", cat: "visual", d: "Генеративное искусство на p5.js с сидами и параметрами." },
  { id: "slack-gif-creator", cat: "visual", d: "Анимированные GIF, оптимизированные под Slack." },

  // Тексты и документы
  { id: "anthropic-skills:storytelling-corrector", cat: "text", used: 2, d: "Правит текст по законам сторителлинга: ритм, конфликт, живость." },
  { id: "anthropic-skills:antidetector", cat: "text", used: 1, d: "Убирает из текста признаки машинной генерации." },
  { id: "docx", cat: "text", used: 1, d: "Создание, чтение и правка Word-документов." },
  { id: "pdf", cat: "text", d: "Всё про PDF: извлечь, склеить, разрезать, заполнить формы." },
  { id: "xlsx", cat: "text", d: "Таблицы Excel: чтение, правка, формулы, графики." },
  { id: "pptx", cat: "text", d: "Презентации: создание, разбор и правка слайдов." },
  { id: "doc-coauthoring", cat: "text", d: "Структурированное соавторство документации, спек, предложений." },
  { id: "internal-comms", cat: "text", d: "Внутренние коммуникации в принятых форматах компании." },
  { id: "writing-fragments", cat: "text", d: "Письмо, фаза 1: добыть сырые фрагменты, без структуры." },
  { id: "writing-beats", cat: "text", d: "Письмо, фаза 2: собрать фрагменты в путь из «битов»." },
  { id: "writing-shape", cat: "text", d: "Письмо, фаза 3: отшлифовать в статью абзац за абзацем." },

  // SEO
  { id: "seo", cat: "seo", used: 1, d: "Комплексный SEO-анализ: аудит, техничка, контент, схемы, GEO." },
  { id: "seo-audit", cat: "seo", d: "Полный аудит сайта с параллельными субагентами." },
  { id: "seo-page", cat: "seo", d: "Глубокий разбор одной страницы." },
  { id: "seo-technical", cat: "seo", d: "Техничка: индексация, краулинг, Core Web Vitals." },
  { id: "seo-content", cat: "seo", d: "Качество контента, E-E-A-T, готовность к AI-цитированию." },
  { id: "seo-content-brief", cat: "seo", d: "Бриф на статью под ключевой запрос." },
  { id: "seo-schema", cat: "seo", d: "Разметка Schema.org в JSON-LD." },
  { id: "seo-sitemap", cat: "seo", d: "Проверка и генерация XML-карт сайта." },
  { id: "seo-geo", cat: "seo", d: "Оптимизация под AI-поиск: AI Overviews, ChatGPT, Perplexity." },
  { id: "seo-local", cat: "seo", d: "Локальное SEO: карточки, NAP, отзывы." },
  { id: "seo-maps", cat: "seo", d: "Позиции на картах, гео-сетки, конкуренты рядом." },
  { id: "seo-cluster", cat: "seo", d: "Кластеризация запросов и hub-and-spoke структура." },
  { id: "seo-plan", cat: "seo", d: "Стратегический SEO-план." },
  { id: "seo-backlinks", cat: "seo", d: "Анализ ссылочного профиля." },
  { id: "seo-images", cat: "seo", d: "Оптимизация изображений для SEO." },
  { id: "seo-hreflang", cat: "seo", d: "Мультиязычность и hreflang." },
  { id: "seo-programmatic", cat: "seo", d: "Программное SEO: страницы по шаблонам в масштабе." },
  { id: "seo-competitor-pages", cat: "seo", d: "Страницы сравнения с конкурентами." },
  { id: "seo-ecommerce", cat: "seo", d: "SEO для интернет-магазинов и маркетплейсов." },
  { id: "seo-sxo", cat: "seo", d: "Search Experience: совпадает ли тип страницы с интентом." },
  { id: "seo-drift", cat: "seo", d: "Слежение за регрессиями SEO по снимкам." },
  { id: "seo-google", cat: "seo", d: "Данные Google: GSC, CrUX, GA4." },
  { id: "seo-dataforseo", cat: "seo", d: "Живые данные выдачи через DataForSEO." },

  // Право РФ
  { id: "check", cat: "law", d: "Проверяет проект на риски 152-ФЗ, 38-ФЗ и ЗоЗПП: формы, cookie, трекеры, ERID." },
  { id: "scan", cat: "law", d: "Сканирует исходники по указанному пути на юр. риски." },
  { id: "scan-url", cat: "law", d: "Открывает живой сайт и проверяет DOM и cookie: согласие, политика, трекеры." },
  { id: "explain-rule", cat: "law", d: "Разбор одного правила: что ищет, как исправить, выдержка из закона." },
  { id: "fix", cat: "law", d: "Исправляет подтверждённые находки и пересканирует." },
  { id: "list-rules", cat: "law", d: "Полный каталог правил: id, серьёзность, статья закона." },
  { id: "get-law", cat: "law", d: "Достаёт текст статьи 152-ФЗ, 38-ФЗ или ЗоЗПП с pravo.gov.ru." },
  { id: "generate-policy", cat: "law", d: "Черновик политики обработки персональных данных." },
];

// Связки — проверенные цепочки скиллов под типовые задачи.
window.COMBOS = [
  { name: "Старт в проекте", icon: "☕", hint: "Сориентироваться за минуту, не читая весь код",
    steps: ["claude-mem:mem-search", "graphify", "claude-mem:smart-explore"] },
  { name: "От идеи до кода", icon: "🌱", hint: "Классический путь фичи — от сырой мысли до ревью",
    steps: ["grilling", "to-spec", "to-tickets", "implement", "tdd", "code-review"] },
  { name: "Большая работа", icon: "🗺", hint: "Когда задача не влезает в одну сессию",
    steps: ["wayfinder", "grill-with-docs", "domain-modeling", "to-tickets", "implement", "handoff"] },
  { name: "Красивый сайт с нуля", icon: "🎨", hint: "Дизайн, картинки, проверка в браузере",
    steps: ["design-taste-frontend", "frontend-design", "kie-image-gen", "impeccable", "webapp-testing", "run"] },
  { name: "Редизайн", icon: "🪄", hint: "Поднять существующий сайт до премиума",
    steps: ["redesign-existing-projects", "high-end-visual-design", "impeccable", "webapp-testing"] },
  { name: "Бренд и визуал", icon: "✨", hint: "Айдентика, иллюстрации, постеры",
    steps: ["brandkit", "kie-image-gen", "canvas-design", "theme-factory"] },
  { name: "Тексты без следов AI", icon: "📜", hint: "От черновых мыслей до живой статьи",
    steps: ["writing-fragments", "writing-beats", "writing-shape", "anthropic-skills:storytelling-corrector", "anthropic-skills:antidetector"] },
  { name: "Документы", icon: "📑", hint: "Прочитать через markitdown, собрать итоговый файл",
    steps: ["pdf", "xlsx", "doc-coauthoring", "docx", "pptx"] },
  { name: "SEO-аудит", icon: "🔎", hint: "От технички до стратегии",
    steps: ["seo-audit", "seo-technical", "seo-content", "seo-schema", "seo-geo", "seo-plan"] },
  { name: "Юр. чистота сайта в РФ", icon: "⚖️", hint: "152-ФЗ, реклама, права потребителей",
    steps: ["check", "scan-url", "explain-rule", "fix", "generate-policy"] },
  { name: "Здоровая архитектура", icon: "🏛", hint: "Глубокие модули и защита репо",
    steps: ["graphify", "improve-codebase-architecture", "codebase-design", "setup-ts-deep-modules", "setup-pre-commit", "git-guardrails-claude-code"] },
  { name: "Автопилот", icon: "⏰", hint: "Регулярные задачи и настройка харнесса",
    steps: ["update-config", "schedule", "claude-mem:standup"] },
];
